name: Setup Gradle Environment
description: Setup Java, Gradle wrapper and required utilities

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        cache-read-only: false

    - name: Ensure gradlew executable
      shell: bash
      run: chmod +x gradlew
