comment:
  layout: "reach, diff, flags"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        # FIXME: target: 80% -> to be reached asap
        target: 50%
