name: Setup Gradle Environment
description: Setup Java and Gradle wrapper

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }} 

    - name: Ensure gradlew executable
      shell: bash
      run: chmod +x gradlew
