name: 🐞 Bug Report
description: Report a bug or unexpected behavior in K2D
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in **K2D – Kotlin 2D Engine**!
        Since the project is currently **Pre-Alpha**, detailed reports are extremely valuable.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe what went wrong.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Create a GameCanvas
        2. Call update/render with ...
        3. The engine crashes / behaves incorrectly
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: k2d-version
    attributes:
      label: K2D Version or Commit
      placeholder: e.g. main@a1b2c3d or 0.1.0
    validations:
      required: true

  - type: input
    id: kotlin-version
    attributes:
      label: Kotlin Version
      placeholder: e.g. 1.9.20
    validations:
      required: true

  - type: input
    id: compose-version
    attributes:
      label: Compose Desktop Version
      placeholder: e.g. 1.5.10
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stacktrace
      description: Paste logs or exceptions here (if any).
      render: shell